name: Docker Image Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read version from elephant.json
      id: project_version
      run: |
        json=$(cat elephant.json)
        version=$(echo $json | grep -oP '"version": "\K(.*?)(?=")')
        echo "::set-output name=version::$version"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/elephant:${{ steps.project_version.outputs.version }}

    - name: Checkout GitOpsElephant repository
      uses: actions/checkout@v2
      with:
        repository: Helga09/GitOpsElephant
        path: GitOpsElephant
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update Docker image tag in elephant.yaml
      run: |
        sed -i 's|image: helga09/elephant:.*|image: helga09/elephant:${{ steps.project_version.outputs.version }}|' GitOpsElephant/my-app/elephant.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'helga09'
        git config --global user.email 'olhavashenko@gmail.com'
        git add .
        git commit -m "Update Docker image tag to ${{ steps.project_version.outputs.version }}"
        git push
