name: Docker Image Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read version from elephant.json
      id: project_version
      run: echo "::set-output name=version::$(jq -r '.version' elephant.json)"