name: Update Docker Image Tag

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read version from elephant.json
      id: project_version
      run: |
        json=$(cat elephant.json)
        version=$(echo $json | grep -oP '"version": "\K(.*?)(?=")')
        echo "::set-output name=version::$version"

    - name: Checkout GitOpsElephant repository
      uses: actions/checkout@v2
      with:
        repository: Helga09/GitOpsElephant
        path: GitOpsElephant
        token: ${{ secrets.GIT_PASSWORD }}

    - name: Update Docker image tag in elephant.yaml
      run: |
        sed -i 's|image: helga09/elephant:.*|image: helga09/elephant:${{ steps.project_version.outputs.version }}|' GitOpsElephant/my-app/elephant.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'helga09'
        git config --global user.email 'olhavashenko@gmail.com'
        git add .
        git commit -m "Update Docker image tag to ${{ steps.project_version.outputs.version }}"
        git push
