name: Docker Image Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read version from elephant.json
      id: project_version
      run: |
        json=$(cat elephant.json)
        version=$(echo $json | grep -oP '"version": "\K(.*?)(?=")')
        echo "::set-output name=version::$version"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/elephant:${{ steps.project_version.outputs.version }}

    - name: Clone the GitOps repository
      run: git clone https://github.com/Helga09/GitOpsElephant.git

    - name: Update the version in elephant.yaml
      run: |
        # Замінюємо версію в файлі elephant.yaml
        sed -i 's/helga09\/elephant:0.0.1/helga09\/elephant:${{ env.PROJECT_VERSION }}/g' GitOpsElephant/my-app/elephant.yaml

    - name: Commit and push the changes
      run: |
        cd GitOpsElephant
        git config --global user.email ${{ secrets.GITHUB_USERNAME }}
        git config --global user.name ${{ secrets.GIT_USERNAME }}
        git add my-app/elephant.yaml
        git commit -m "Update the version in elephant.yaml"
        git push
