name: Docker Image Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read version from file
      id: version
      run: echo "::set-output name=version::$(cat ver.txt)"

    - name: Print version
      run: echo "Version: ${{ steps.version.outputs.version }}"
